name: Smoke (synth+eval)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      CUDA_VISIBLE_DEVICES: ""
      TF_CPP_MIN_LOG_LEVEL: "2"
      CFG: configs/config.yaml
      SMOKE_MODEL: gan
      # Make repo-local gcs_core importable
      PYTHONPATH: ${{ github.workspace }}/gcs-core:${{ env.PYTHONPATH }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.10 (TF-friendly)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python - <<'PY'
          import sys
          print("Python:", sys.version)
          try:
              import tensorflow as tf; print("TensorFlow:", tf.__version__)
          except Exception as e:
              print("TF import failed:", e)
          try:
              import gcs_core; print("gcs_core:", gcs_core.__file__)
          except Exception as e:
              print("gcs_core import failed:", e)
          PY

      - name: Smoke test (synth + eval)
        run: |
          make smoke SMOKE_MODEL=${SMOKE_MODEL} CFG=${CFG}

      - name: Collect scores table
        if: always()
        run: |
          mkdir -p ci_out
          python scripts/collect_scores.py || true
          cp -r artifacts ci_out/artifacts || true
          cp artifacts/phase1_scores.csv ci_out/ 2>/dev/null || true

      - name: Upload artifacts (summaries, grids, table)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: ci_out
          if-no-files-found: warn
